services:
# TODO: use ENV vars to make config easier
  database:
    image: mysql:9.4
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony_app
        MYSQL_USER: app_user
        MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
