nelmio_api_doc:
    type_info: true
    documentation:
        info:
            title: VL.ru OFF API
            description: API для управления отключениями электроэнергии и воды
            version: 1.0.0
